function [config] = simulation_config_wrapper(ntarget, reward, Use_Void, rotation_time, pd, scenario)
    % some global parameter
    planning_interval = 10 + rotation_time;
    noise_sigma = 4;
    noise_gen = 4;
    lookahead = 3;
    likelihood_type = Likelihood_Type.imprecise;
	noise_cov = diag([2.5, 2.5, 0.0025]);

    threshold = 2e4; %2e6 must be use for RSSI only in mountain terrain (Scenario2_boorowa)
    target_id_list = (1:ntarget);

	switch scenario
	case 'Scenario1.mat'
		imprecision_range = repmat([-6; 1], 1, ntarget);  % flat
    	DEM_file = 'flat_DEM';
	case 'Scenario2_boorowa.mat'
    	imprecision_range = repmat([-40; 20], 1, ntarget);  % boorowa
    	DEM_file = 'Boorowa_DEM';
	case 'Scenario11_Kangaroo_alt.mat'
		imprecision_range = repmat([-16; 10], 1, ntarget);
		DEM_file = 'Kangaroo_alt';
	end

    term_cond = Termination_Method.det;
	Sensitivity = -120;

    % setup truth target configuration
    birth_state = [1408.7, 1119.6, 1698.1, 923.8, 1379.3, 698.9, 1594.3, 1169.5, 333.2,  676.7,  537.0, 1630.9, 1260.1, 1035.6, 767.4, 464.8,  1207.3, 541.9,  767.9,  1176.4; ...
                   1406.2, 1658.3, 1386.5, 898.1, 555.6,  773.4, 901.2,  1054.2, 1167.7, 1432.4, 491.0, 985.9,  1184.8, 283.5,  507.2, 1248.3, 1199.1, 1674.2, 1200.4, 753.4;  ...
                   0.2, 0.2, 0.2,  0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2];
    
    birth_state = birth_state(:, 1:ntarget);
    birth_death = repmat([1;1e30], 1, ntarget);
    P0_truth = 40*ones(1,ntarget);
    P0_model = 40*ones(1,ntarget);
    frequency = 150e6+1e4*(1:ntarget);
    path_loss_truth = 4*ones(1,ntarget);
    path_loss_model = 4*ones(1, ntarget);
    tree_h = ones(1,ntarget);
    

    %% Simulation configuration
    % wrapper for each module's settings

    % setup measurements generator
    sim_sensor_config = init_sim_sensor_config(...
        'Antenna'    ,      Antenna_Type.H,...
        'Pd'         ,      pd,...
        'Sensitivity',      Sensitivity,...
        'Sigma'      ,      noise_gen ...
     );


    sim_target_config = init_sim_target_config( ...
        'Ntarget',           ntarget,...
        'Mode',              'WD',...
        'nx',                3,...
        'dt',                1,...
        'Noise_Cov',         diag([2.5, 2.5, 0]),...
        'Transition_Model',  eye(3),...
        'Init_State',        birth_state, ...
        'Birth_Death',       birth_death ...
    );
                                          

    % setup target transmitter 
    sim_target_radio_config = init_sim_target_radio_config( ...
        'NTarget',      ntarget, ...
        'P0',           P0_truth,...
        'Frequency',    frequency,...
        'Path_Loss',    path_loss_truth,...
        'Tree_Height',  tree_h...
     );

    %=====================================================================================

    %% Setup System configurations

    % setup area
    area_config = init_area_config( ...
                    'Vertex', [1,1; 1, 2000; 2000, 2000; 2000, 1; 1,1]', ...
                    'DEM', DEM_file);
                
    % setup uav parameter
    uav_config = init_uav_config( ...  
        'traject_time', planning_interval, ...
        'rotation_time', rotation_time ...
    );         

    % setup sensor config - system
    RSSI_sensor_config = init_RSSI_sensor_config( ...
        'Antenna',          Antenna_Type.H, ... 
        'Sensitivity',      Sensitivity, ...
        'Sigma_RSSI',       noise_sigma, ...
        'Path_Loss',        path_loss_model, ...
        'P0',               P0_model, ...
        'Likelihood_Type',  likelihood_type, ...
        'Imprecision_Range', imprecision_range, ...
        'target_id_list', target_id_list ...
    );
    AoA_sensor_config = init_AoA_sensor_config( ...
        'Antenna',          Antenna_Type.H, ... 
		'Sigma_aoa',		sqrt(0.095) ...
    );

    % setup target model
    target_config = init_target_config( ...
        'Ntarget',          ntarget, ...
        'Mode',             'WD',...
        'nx',               3,...
        'dt',               1,...
		'Noise_Cov',        noise_cov,...
        'Transition_Model', eye(3)...
    );

    % setup planner
    planner_config = init_planner_config( ...
     'alpha',               0.1, ...
     'Discount',            1, ...
     'Heading_number',      8, ...
     'T',                   planning_interval,...
     'Variable_lookahead',  false, ...
     'Lookahead',           lookahead, ...
     'Use_Void',            Use_Void, ...
     'Void_r',              50, ...
     'Void_th', 	        0.95, ...
     'Mode',                Planning_Meas_Mode.PIMS, ...
     'Reward',              reward, ...
     'Plan_target',         'Closest', ...
     'Planning_sample',     1000, ...
     'Density_type',        Density_Type.Particle, ...
     'Rotation_time',       rotation_time ...
   );


    % setup filter
    RSSI_filter_config = init_RSSI_filter_config( ...
        'cz', 1/abs(Sensitivity),...
        'nx', 3,...
        'Pb', 1e-5,...
        'Pd', pd,...
        'Pf', 0.05,...
        'Ps', 0.99, ...
        'Regularized', false ...
    );

    AoA_filter_config = init_AoA_filter_config( ...
        'cz', 1/(2*pi),...
        'nx', 3,...
        'Pb', 1e-5,...
        'Pd', 0.9,...
        'Pf', 0.05,...
        'Ps', 0.99, ...
        'Regularized', false ...
    );

    AoA_config = init_bearing_config( ...
        'Interpolate_factor', 10, ...
        'Antenna', Antenna_Type.H, ...
        'Move_time', planning_interval - rotation_time, ...
        'Samples', rotation_time ...
        );
    
    Term_config = init_term_config(term_cond, threshold);

                                
config.sim_sensor_config = sim_sensor_config;
config.sim_target_config = sim_target_config;
config.sim_target_radio_config = sim_target_radio_config;
config.area_config = area_config;
config.uav_config = uav_config;
config.RSSI_sensor_config = RSSI_sensor_config;
config.AoA_sensor_config = AoA_sensor_config;
config.target_config = target_config;
config.planner_config = planner_config;
config.RSSI_filter_config = RSSI_filter_config;   
config.AoA_filter_config = AoA_filter_config;
config.AoA_config = AoA_config;
config.Term_config = Term_config;
config.target_id_list = target_id_list;         
end